export const Types = {

    MGRespondMessages: '[MG] respond message',
    MGStopRespondMessages: '[MG] stop respond message',
    MGScrollMessageOutGing: '[MG] scroll message outgoing',
    MGScrollMessageClear: '[MG] scroll message clear',
    MGRemoveMessage: '[MG] remove message',
    // 
    ivgetImageVideo: '[IV] get ImageVideo',
    ivcreateImageVideo: '[IV] create ImageVideo',
    ivUploadFinish: '[IV] upload finish',
    ivUpload: '[IV] upload',
    ivSetImageVideo: '[IV] set ImageVideo',
    ivClearSetImageVideo: '[IV] clear set ImageVideo',
    ivUpdateImageVideo: '[IV] update ImageVideo',
    ivDeleteImageVideo: '[IV] delete ImageVideo',
    // 
    pgrActivePaginate: '[Auth] active paginate',
    pgrClearActivePaginate: '[Auth] clear active paginate',
    // 
    chbUpload: '[chb] upload',
    chbUploadFinish: '[chb] upload finish',
    // 
    blgetBeleaver: '[BL] get beleaver',
    blcreateBeleaver: '[BL] create beleaver',
    blUploadFinish: '[BL] upload finish',
    blUpload: '[BL] upload',
    blSetBeleaver: '[BL] set beleaver',
    blClearSetBeleaver: '[BL] clear set beleaver',
    blUpdateBeleaver: '[BL] update beleaver',
    blDeleteBeleaver: '[BL] delete beleaver',
    // 
    nbgetVideo: '[NB] get Zooms',
    nbcreateVideo: '[NB] create Video',
    nbSetVideo: '[NB] set Video',
    nbSetVideoForm: '[NB] set Video form',
    nbClearSetVideo: '[NB] clear set Video',
    nbUpdateVideo: '[NB] update Video',
    nbDeleteVideo: '[NB] delete Video',
    nbUpload: '[NB] upload nb',
    nbUploadFinish: '[NB] upload finish nb',
    // 
    vwdgetVideosWordOfTheDay: '[VWD] get VideosWordOfTheDay',
    vwdcreateVideoWordOfTheDay: '[VWD] create VideoWordOfTheDay',
    vwdSetVideoWordOfTheDay: '[VWD] set VideoWordOfTheDay',
    vwdSetVideoWordOfTheDayForm: '[VWD] set VideoWordOfTheDay form',
    vwdClearSetVideoWordOfTheDay: '[VWD] clear set VideoWordOfTheDay',
    vwdUpdateVideoWordOfTheDay: '[VWD] update VideoWordOfTheDay',
    vwdDeleteVideoWordOfTheDay: '[VWD] delete VideoWordOfTheDay',
    vwdUpload: '[VWD] upload vwd',
    vwdUploadFinish: '[VWD] upload finish vwd',
    vwdPaginateVideo: '[VWD] paginate video',
    // 
    ntDeleteNotification: '[NT] delete notification',
    ntNotificacionesCargadas: '[NT] notificaciones cargadas',
    ntCargarNotificaciones: '[NT] cargar notificaciones',
    ntRemoveNewNotificaciones: '[NT] remove new notificaciones',
    // 
    chtTyping: '[CHT] typing',
    chtScrollChat: '[CHT] scroll chat',
    chtImageMessage: '[CHT] image message',
    chtClearState: '[CHT] clear state',
    chtUsuariosCargados: '[CHT] usuarios cargados',
    chtCargarChat: '[CHT] cargar chat',
    chtActiveChat: '[CHT] active chat',
    chtActiveMessage: '[CHT] active message',
    chtClearChatActive: '[CHT] clear chat active',
    // 
    skStatusSocket: '[SK] status socket',
    // 
    ytgetYoutube: '[YT] get Youtube',
    ytcreateYoutube: '[YT] create Youtube',
    ytSetYoutube: '[YT] set Youtube',
    ytSetYoutubeForm: '[YT] set Youtube form',
    ytClearSetYoutube: '[YT] clear set Youtube',
    ytUpdateYoutube: '[YT] update Youtube',
    ytDeleteYoutube: '[YT] delete Youtube',
    ytPaginateYoutube: '[YT] paginate Youtube',
    // 
    cogetContacts: '[CO] get Contacts',
    cocreateContact: '[CO] create Contact',
    coSetContact: '[CO] set Contact',
    coSetContactForm: '[CO] set Contact form',
    coClearSetContact: '[CO] clear set Contact',
    coUpdateContact: '[CO] update Contact',
    coDeleteContact: '[CO] delete Contact',
    coPaginateContact: '[CO] paginate Contact',
    coCargarContact: '[CO] cargar Contact',
    // 
    cagetCapsules: '[CA] get Capsules',
    catcreateCapsule: '[CA] create Capsule',
    catSetCapsule: '[CA] set Capsule',
    catClearSetCapsule: '[CA] clear set Capsule',
    catUpdateCapsule: '[CA] update Capsule',
    catDeleteCapsule: '[CA] delete Capsule',
    caPaginateCapsule: '[CA] paginate Capsule',
    caUpload: '[CA] upload ca',
    caUploadFinish: '[CA] upload finish ca',
    // 
    gagetGallerys: '[GA] get Gallerys',
    gacreateGallery: '[GA] create Gallery',
    gaSetGallery: '[GA] set Gallery',
    gaSetGalleryForm: '[GA] set Gallery form',
    gaClearSetGallery: '[GA] clear set Gallery',
    gaUpdateGallery: '[GA] update Gallery',
    gaDeleteGallery: '[GA] delete Gallery',
    gaPaginateGallery: '[GA] paginate Gallery',
    gaUpload: '[chb] upload ga',
    gaUploadFinish: '[chb] upload finish ga',
    // 
    magetMains: '[Ma] get Mains',
    macreateMain: '[Ma] create Main',
    maSetMain: '[Ma] set Main',
    maSetMainForm: '[Ma] set Main form',
    maClearSetMain: '[Ma] clear set Main',
    maUpdateMain: '[Ma] update Main',
    maDeleteMain: '[Ma] delete Main',
    maPaginateMain: '[MA] paginate Main',
    maUpload: '[MA] upload ma',
    maUploadFinish: '[MA] upload finish ma',
    // 
    zmgetZooms: '[ZM] get Zooms',
    zmcreateZoom: '[ZM] create Zoom',
    zmSetZoom: '[ZM] set Zoom',
    zmSetZoomForm: '[ZM] set Zoom form',
    zmClearSetZoom: '[ZM] clear set Zoom',
    zmUpdateZoom: '[ZM] update Zoom',
    zmDeleteZoom: '[ZM] delete Zoom',
    zmUpload: '[ZM] upload zm',
    zmUploadFinish: '[ZM] upload finish zm',
    // 
    evgetEvents: '[EV] get Events',
    evcreateEvent: '[EV] create Event',
    evSetEvent: '[EV] set Event',
    evSetEventForm: '[EV] set Event form',
    evClearSetEvent: '[EV] clear set Event',
    evUpdateEvent: '[EV] update Event',
    evDeleteEvent: '[EV] delete Event',
    evPaginateEvent: '[EV] paginate Event',
    evUpload: '[EV] upload ev',
    evUploadFinish: '[EV] upload finish ev',
    // 
    ptgetPetitions: '[PT] get Petitions',
    ptgetPetitionesUser: '[PT] get PetitionesUser',
    ptgetPetitionSinCuenta: '[PT] get Petition Sin Cuenta',
    ptcreatePetition: '[PT] create Petition',
    ptSetPetition: '[PT] set Petition',
    ptSetPetitionesUser: '[PT] set Petitiones User',
    ptSetPetitionSinCuenta: '[PT] set Petition Sin Cuenta',
    ptSetPetitionForm: '[PT] set Petition form',
    ptClearSetPetition: '[PT] clear set Petition',
    ptUpdatePetition: '[PT] update Petition',
    ptDeletePetition: '[PT] delete Petition',
    ptDeletePetitionesUser: '[PT] delete Petitiones User',
    ptDeletePetitionSinCuenta: '[PT] delete Petition Sin Cuenta',
    ptPaginatePetition: '[PT] paginate petition',
    ptPaginatePetitionUser: '[PT] paginate petition user',
    ptPaginatePetitionSinCuenta: '[PT] paginate petition sin cuenta',
    ptCargarPeticionesUser: '[PT] cargar peticiones user',
    ptCargarPeticionesSinCuenta: '[PT] cargar peticiones sin cuenta',
    ptCargarPeticionesPastores: '[PT] cargar peticiones pastores',
    // 
    usSetUser: '[US] set user',
    // 
    migetSeries: '[Mi] get series',
    micreateSerie: '[Mi] create serie',
    miSetSerie: '[Mi] set serie',
    miSetSerieForm: '[Mi] set serie form',
    miClearSetSerie: '[Mi] clear set serie',
    miUpdateSerie: '[Mi] update serie',
    miDeleteSerie: '[Mi] delete serie',
    miPaginateSerie: '[Mi] paginate serie',
    miUpload: '[Mi] upload mi',
    miUploadFinish: '[Mi] upload finish mi',
    // 
    sktgetBosquejos: '[SKT] get bosquejos',
    sktcreateBosquejo: '[SKT] create bosquejo',
    sktSetBosquejo: '[SKT] set bosquejo',
    sktClearSetBosquejo: '[SKT] clear set bosquejo',
    sktUpdateBosquejo: '[SKT] update bosquejo',
    sktDeleteBosquejo: '[SKT] delete bosquejo',
    sktPaginateBosquejo: '[SKT] paginate bosquejo',
    sktUpload: '[SKT] upload skt',
    sktUploadFinish: '[SKT] upload finish skt',
    // 
    authChecking: '[Auth] checking login state',
    authCheckingFinish: '[Auth] finish checking login state',
    authLogin: '[Auth] login ',
    authStartRegister: '[Auth] start register ',
    authStartGetUsers: '[Auth] start Get Users ',
    authStartUpdateUser: '[Auth] start update User ',
    authStartUpdateUserAdmin: '[Auth] start update User admin ',
    authStartDeleteUser: '[Auth] start delete User ',
    authStartTokenRenew: '[Auth] start token renew ',
    authLogout: '[Auth] logout ',
    authSetUser: '[Auth set user',
    authSetUserAdmin: '[Auth set user admin',
    authDeleteUser: '[Auth] delete user',
    authPaginateUser: '[Auth] paginate user',
    authModalOpen: '[Auth] modal open',
    authModalClose: '[Auth] modal close',
    authModalOpenCreate: '[Auth] modal open create',
    authModalCloseCreate: '[Auth] modal close create',
    authUpload: '[Auth] upload auth',
    authUploadFinish: '[Auth] upload finish auth',
    authForgotPassword: '[Auth forgot password',
    authsetNotificationPost: '[Auth] set notifications post',
    authUserUsuariosget: '[Auth] User usuarios get'
}